proxy/src/main/java/com/velocitypowered/proxy/protocol/ProtocolConstants.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/StateRegistry.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/ClientSettings.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/JoinGame.java

Implemented the 1.8 protocol by reversing the 1.8 to 1.9 changelog on https://wiki.vg/Protocol_History. I have tested this with a variety of different actions/packets and it seems to function correctly. 
Closes #9.

Add 1.8 support

---

.gitignore
api/src/main/java/com/velocitypowered/api/proxy/Player.java
proxy/src/main/java/com/velocitypowered/proxy/connection/backend/BackendPlaySessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/StateRegistry.java
proxy/src/test/java/com/velocitypowered/proxy/protocol/PacketRegistryTest.java

When player switch a server, velocity sends a login packet and when client receive packet it creates a new playerController/worldController objects where client store all scoreboards. We dont need to store scoreboards in memory.
Tested on MC 1.8.9, 1.12.2 and 1.13.

Don't handle scoreboards from backend server

---

api/src/main/java/com/velocitypowered/api/command/CommandSource.java
api/src/main/java/com/velocitypowered/api/event/EventManager.java
api/src/main/java/com/velocitypowered/api/event/permission/PermissionsSetupEvent.java
api/src/main/java/com/velocitypowered/api/permission/PermissionFunction.java
api/src/main/java/com/velocitypowered/api/permission/PermissionProvider.java
api/src/main/java/com/velocitypowered/api/permission/PermissionSubject.java
api/src/main/java/com/velocitypowered/api/permission/Tristate.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/LoginSessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/plugin/VelocityEventManager.java

My aims with this were, in no particular order:
* Easy/simple to use
* Straight forward to implement, delegating *all* handling to the plugin managing permissions
* Fast in terms of performance
I've borrowed a few concepts from other areas of the MC ecosystem, namely
* `Tristate` from [Sponge](https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/util/Tristate.java) & [LuckPerms](https://github.com/lucko/LuckPerms/blob/master/api/src/main/java/me/lucko/luckperms/api/Tristate.java).
* `PermissionSubject` from [Sponge](https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/service/permission/Subject.java), although only the name is copied. The interface is really just a simple version of Bukkit's `Permissible`.
* …

Permissions!

---

api/src/main/java/com/velocitypowered/api/util/GameProfile.java
proxy/src/main/java/com/velocitypowered/proxy/connection/MinecraftConnection.java
proxy/src/main/java/com/velocitypowered/proxy/connection/VelocityConstants.java
proxy/src/main/java/com/velocitypowered/proxy/connection/backend/BackendPlaySessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/backend/LoginSessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/backend/VelocityServerConnection.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/HandshakeSessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/LoginSessionHandler.java

Add support for Forge 1.8-1.12
For the most part, we don't need to intercept `FML|HS` packets, except to detemine when to tell the client to reset the handshake ready for a new one. That's what most of this code actually does. It also implements my `GameProfile` method of indicating to SpongeForge that the incoming client is a Forge client.
Happy for comments/reviews etc. It is a relatively unintrusive change and does not affect Vanilla play.

Forge Support

---

proxy/src/main/java/com/velocitypowered/proxy/connection/backend/LoginSessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java

Simply moved setting the "can send reset packet" status to the client play handler, as that has a branch that is only executed during the first join (after the FML handshake will have completed first time)
Untested, will test later if someone doesn't get there before me (but it should work!)
Fixes #69 (again)

Don't fire a FML reset packet on first login, set it as required for the second join after the first completes

---

proxy/src/main/java/com/velocitypowered/proxy/connection/backend/VelocityServerConnection.java
proxy/src/main/java/com/velocitypowered/proxy/network/ConnectionManager.java
proxy/src/main/java/com/velocitypowered/proxy/network/Connections.java

For some reason having a read timeout handler is not enough. Without this option players will randomly timeout from backend servers.

Add CONNECT_TIMEOUT_MILLIS to fix timeout errors.

---

api/src/main/java/com/velocitypowered/api/proxy/server/ServerPing.java

This will allow server owners to change the server type during a proxy ping event. This only has effect when the proxy is announcing itself with forge support.
When forced hosts are implemented it might be a good thing to make this configurable per server.

Allow modifying the ModInfo type.

---

api/src/main/java/com/velocitypowered/api/proxy/server/ServerPing.java

Once forced hosts are implemented this will allow caching of mod lists and the ability return them during proxy ping events.

Modinfo: Add getType and getModList methods.

---

.gitignore

Although the gitignore.io template does a decent job, it isn't broad enough to cover all of the files generated by IDEA. :(

Fix/improve gitignore file to fully cover all IntelliJ IDEA files

---

api/src/main/java/com/velocitypowered/api/command/Command.java
api/src/main/java/com/velocitypowered/api/permission/PermissionFunction.java
api/src/main/java/com/velocitypowered/api/permission/PermissionSubject.java
proxy/src/main/java/com/velocitypowered/proxy/VelocityServer.java
proxy/src/main/java/com/velocitypowered/proxy/command/ServerCommand.java
proxy/src/main/java/com/velocitypowered/proxy/command/ShutdownCommand.java
proxy/src/main/java/com/velocitypowered/proxy/command/VelocityCommand.java
proxy/src/main/java/com/velocitypowered/proxy/command/VelocityCommandManager.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java

This allows plugins to customize which players can use their commands. For players without permission, the command is effectively invisible, and the handling is passed through to the backend server.
Will conflict with #98 (depending on what gets merged first, if any)

Implement optional permission check method for commands

---

proxy/src/main/java/com/velocitypowered/proxy/VelocityServer.java
proxy/src/main/java/com/velocitypowered/proxy/config/AnnotatedConfig.java
proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java

Example: if user removes `[forced-hosts]` section from configuration and (obviously) has modified `[server]` section with server names which aren't in forced hosts default configuration, then configuration validation would fail on startup, but file wouldn't get re-saved with default values.
Also I moved and renamed key escaping/unescaping methods to AnnotatedConfig class.

Fix configuration saving

---

proxy/src/main/java/com/velocitypowered/proxy/VelocityServer.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/LoginSessionHandler.java

This PR will fix a error caused when plugins try to send a title, message, header and footer, etc during login event. https://pastebin.com/Uwu9Q48f .

register player connection only when switched to PLAY state

---

api/src/main/java/com/velocitypowered/api/proxy/ProxyServer.java
proxy/src/main/java/com/velocitypowered/proxy/VelocityServer.java

Would be great to not have to implement these methods in every plugin that might use them. Bungeecord has implemented matchPlayer, but not matchServer. 
Edit: all checkstyle warnings fixed

Add matchPlayer and matchServer

---

proxy/src/main/java/com/velocitypowered/proxy/VelocityServer.java

As @creeper123123321 noted on Discord, the javadoc specifies "Matches all {@link Player}s whose names start with the provided partial name.".
With the current implementation, if there were two online players named Notch and Notch2, only Notch would be returned as a singleton Collection. This PR fixes this behavior by removing the `exactMatch` code.

Fix implementation of #176

---

native/src/main/java/com/velocitypowered/natives/compression/JavaVelocityCompressor.java

In certain situations a client will fail to connect with an exception of `DataFormatException: unknown compression method` or `DataFormatException: incorrect header check`, this fixes that.
This was tested with a Direwolf20 modpack client against a SpongeVanilla server, the unknown compression method error happened with a localhost connection, the incorrect header check happened with the client connecting from outside the network.

Fix DataFormatException with java decompression

---

proxy/src/main/java/com/velocitypowered/proxy/tablist/VelocityTabListLegacy.java

I forgot to clear the name mapping upon server switch, which lead to weird duplicate entries.

Completely clear legacy tablist on server switch

---

native/src/main/java/com/velocitypowered/natives/encryption/JavaVelocityCipher.java
native/src/main/java/com/velocitypowered/natives/encryption/NativeVelocityCipher.java
native/src/main/java/com/velocitypowered/natives/encryption/VelocityCipher.java
native/src/main/java/com/velocitypowered/natives/util/BufferPreference.java
native/src/main/java/com/velocitypowered/natives/util/MoreByteBufUtils.java
native/src/test/java/com/velocitypowered/natives/encryption/VelocityCipherTest.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/netty/MinecraftCipherDecoder.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/netty/MinecraftCipherEncoder.java

All AES implementations being used are 'copy safe', where the source and
destination arrays may be the same. Lets save ourself a copy and reap
the performance wins!

Make AES crypto operations no-copy

---

proxy/src/main/java/com/velocitypowered/proxy/tablist/VelocityTabListLegacy.java

Fixes #282
Text below is copied from the commit message:
> The 1.7 tablist packet only contains three types of information:
> 
>  - Name of the tablist entry (limited to 16 characters including colors)
>  - Ping of the entry
>  - If this entry needs to be added or removed (client accepts duplicates
>  as 'ping update')
> 
> The previous logic was trying to preserve parity with
> GameProfile#getName returning a stripped down name to have a 'real'
> username.
> That is fundamentally broken, because entries with duplicate content,
> but different colors are very common, especially with custom tablists.
> 
> For packets coming from a native 1.7 server we just won't define the
> displayname anymore, as there is no such thing as a 'displayname',
> because tablist entries are not bound to any …

Fix tablist behaving wrong with colors (1.7) (Fixes #282)

---

proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java

Server names that don't match [A-Za-z0-9_-] fail to parse unless wrapped in quotes. The TOML api leaves these quotes in place when reading the key which leads to unintended name behavior.

Clean server name keys before attempting to register

---

proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java

before:
```toml
player-info-forwarding-mode = "NONE"
```
after:
```toml
player-info-forwarding-mode = "NONE"
```

Fix config formatting

---

api/src/main/java/com/velocitypowered/api/command/Command.java
api/src/main/java/com/velocitypowered/api/command/RawCommand.java
proxy/src/main/java/com/velocitypowered/proxy/command/VelocityCommandManager.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/console/VelocityConsole.java

Fairly simple.
To use them, the developer should still implement sync ones for plugins which depends on others' suggestions. Whether this includes data fetched from e.g. a database is up to them.

Add async suggestions

---

api/src/main/java/com/velocitypowered/api/event/connection/PluginMessageEvent.java

Adds the method `dataAsInputStream()` to `PluginMessageEvent`. This allows for multiple reads of the data without unnecessary copying. Note that `ByteArrayInputStream` does not allow modifications of the underlying array, so it is still safe.

Add dataAsInputStream() to PluginMessageEvent

---

api/src/main/java/com/velocitypowered/api/proxy/ProxyServer.java
proxy/src/main/java/com/velocitypowered/proxy/VelocityServer.java

Add shutdown methods to the ProxyServer interface. I left out the `explicit` parameter because it seemed like an unnecessary complexity for the API.

Add shutdown methods to ProxyServer

---

api/src/main/java/com/velocitypowered/api/proxy/config/ProxyConfig.java
proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/LoginSessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/network/ServerChannelInitializer.java
proxy/src/main/resources/default-velocity.toml

Made it so initial timeout for connections is configurable.
Timeout is restored back later when user switches to PLAY state.

Make initial read timeout configurable

---

proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java

As of commit https://github.com/KyoriPowered/adventure/commit/98dd0aa015e475aa2dac3668490a7bc85b992fc9, the methods `Title#fadeInTime()`, `Title#stayTime()` and `Title#fadeOutTime()` no longer exist.

Fix kyori adventure title

---

build.gradle

a quick drive-by on the web editor
dropped the sponge repo because versions 3.7+ are now on maven central

bump configurate to 3.7.1

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
proxy/build.gradle

junit: 5.3.0-M1 -> 5.7.0
slf4j: 1.7.25 -> 1.7.30
netty: 4.1.51.Final -> 4.1.52.Final
guava: 25.1-jre -> 29.0-jre
checkerFramework: 2.7.0 -> 3.6.1
jline-terminal-jansi: 3.12.1 -> 3.16.0
fastutil: 8.2.3 -> 8.4.1
async-http-client: 2.10.4 -> 2.12.1
completable-futures: 0.3.2 -> 0.3.3
gradle-wrapper: 6.6 -> 6.6.1
BREAKING CHANGE: No breaking change

Track some dependency updates
