proxy/src/main/java/com/velocitypowered/proxy/VelocityServer.java

Fix unregisterConnection using non-lowercase username

---

native/src/main/java/com/velocitypowered/natives/util/Natives.java
proxy/src/main/java/com/velocitypowered/network/ConnectionManager.java
proxy/src/main/java/com/velocitypowered/proxy/Velocity.java
proxy/src/main/java/com/velocitypowered/proxy/VelocityServer.java

```
[01:35:49 INFO]: Booting up Velocity...
[01:35:49 INFO]: Connections will use epoll channels, native (Linux amd64) compression, Java ciphers
[01:35:49 INFO]: Listening on /0:0:0:0:0:0:0:0%0:25565
```

minor shuffle to log messages

---

proxy/src/main/java/com/velocitypowered/proxy/Velocity.java

Feel free to suggest formatting changes

Add startup time to log messages

---

proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java

Taken from #14. I just needed a reason to clone it and check out the codebase :)
Tell me if something else is wanted with this feature.
Closes #11

Fallback to next server on connection error

---

.gitignore
api/src/ap/java/com/velocitypowered/api/plugin/ap/SerializedPluginDescription.java
api/src/main/java/com/velocitypowered/api/plugin/Plugin.java
api/src/main/java/com/velocitypowered/api/plugin/PluginDescription.java
api/src/main/java/com/velocitypowered/api/plugin/meta/PluginDependency.java
proxy/src/main/java/com/velocitypowered/proxy/plugin/loader/JavaPluginLoader.java
proxy/src/main/java/com/velocitypowered/proxy/plugin/loader/VelocityPluginContainer.java
proxy/src/main/java/com/velocitypowered/proxy/plugin/loader/VelocityPluginDescription.java
proxy/src/main/java/com/velocitypowered/proxy/plugin/loader/java/JavaVelocityPluginDescription.java
proxy/src/main/java/com/velocitypowered/proxy/plugin/loader/java/SerializedPluginDescription.java
proxy/src/test/java/com/velocitypowered/proxy/testutil/FakePluginManager.java

- Add plugin (display) name, description and plugin URL
- Make everything except plugin ID optional (instead of empty string)
- Exclude empty properties from generated velocity-plugin.json
- Make plugin author list immutable
- Other (minor) cleanup and refactoring

Various improvements to plugin metadata

---

.gitignore
api/src/main/java/com/velocitypowered/api/event/ResultedEvent.java
api/src/main/java/com/velocitypowered/api/event/connection/PreLoginEvent.java
api/src/main/java/com/velocitypowered/api/event/player/gameprofile/GameProfileRequestEvent.java
api/src/main/java/com/velocitypowered/api/proxy/Player.java
api/src/main/java/com/velocitypowered/api/util/GameProfile.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/LoginSessionHandler.java

This will be useful for auth plugins on offline mode servers. Eg to allow player to not use '/login' command on join if he login using a licensed account

Allow to enable online mode for player connection

---

api/src/main/java/com/velocitypowered/api/event/ResultedEvent.java

Fix ResultedEvent.GenericResult.DENIED

---

api/src/main/java/com/velocitypowered/api/event/player/PlayerSettingsChangedEvent.java
api/src/main/java/com/velocitypowered/api/playersettings/PlayerSettings.java
api/src/main/java/com/velocitypowered/api/playersettings/SkinParts.java
api/src/main/java/com/velocitypowered/api/proxy/Player.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientSettingsWrapper.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/ClientSettings.java

Sorry that there is no JavaDocs, my english is bad to correctly construct a sentence.

Add PlayerSettings API

---

api/src/main/java/com/velocitypowered/api/proxy/Player.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java

add method to get player ping

---

proxy/src/main/java/com/velocitypowered/proxy/connection/backend/LoginSessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java

Fixes #69 - see that for discussion

Ensure the reset packet is not sent when Forge isn't expecting it.

---

api/src/main/java/com/velocitypowered/api/event/connection/PreLoginEvent.java

Sorry for that. Ide shows that all is good.

fix compile

---

proxy/src/main/java/com/velocitypowered/proxy/connection/VelocityConstants.java
proxy/src/main/java/com/velocitypowered/proxy/connection/backend/VelocityServerConnection.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java

Only send FML/FML|MP plugin messages if the player has joined the server

---

api/src/main/java/com/velocitypowered/api/proxy/Player.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/Chat.java

Not totally sure on the method name - my aim was to make it super clear what the method did, to avoid confusion with the sendMessage method.

Implement Player#spoofChatInput method

---

proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/netty/GS4QueryHandler.java

Add an option in the config to change the query map

---

api/src/main/java/com/velocitypowered/api/proxy/Player.java
api/src/main/java/com/velocitypowered/api/proxy/player/TabList.java
api/src/main/java/com/velocitypowered/api/proxy/player/TabListEntry.java
proxy/src/main/java/com/velocitypowered/proxy/connection/MinecraftSessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/backend/BackendPlaySessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/backend/LoginSessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/ProtocolUtils.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/StateRegistry.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/PlayerListItem.java
proxy/src/main/java/com/velocitypowered/proxy/tablist/VelocityTabList.java
proxy/src/main/java/com/velocitypowered/proxy/tablist/VelocityTabListEntry.java

This PR adds the ability to read, modify, add and remove entries from a player's tab list.
I will add the documentation once all the other parts of the PR have been approved.
Resolves #67.

Tab List Modification

---

api/src/main/java/com/velocitypowered/api/proxy/ProxyServer.java
api/src/main/java/com/velocitypowered/api/proxy/config/ProxyConfig.java
proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java
proxy/src/main/java/com/velocitypowered/proxy/connection/backend/VelocityServerConnection.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/LoginSessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/StatusSessionHandler.java

This adds the preliminary code to have access to the proxy configuration values through the API. Picked up from #77 after inactivity for some time. No javadocs as of yet

Added ProxyConfig interface and implemented in VelocityConfiguration

---

api/src/main/java/com/velocitypowered/api/event/query/ProxyQueryEvent.java
api/src/main/java/com/velocitypowered/api/event/query/package-info.java
api/src/main/java/com/velocitypowered/api/proxy/config/ProxyConfig.java
api/src/main/java/com/velocitypowered/api/proxy/server/QueryResponse.java
proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/netty/GS4QueryHandler.java

[WIP] GS4 query event

---

api/src/main/java/com/velocitypowered/api/proxy/config/ProxyConfig.java
proxy/src/main/java/com/velocitypowered/proxy/config/AnnotatedConfig.java
proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java

[WIP] Forced hosts configuration support

---

proxy/src/main/java/com/velocitypowered/proxy/config/AnnotatedConfig.java
proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java

In this PR I try to fix bad code style, comments and documentation where I stumbled upon when I tinkered on this project.
Suggestions are welcome.
Notes/TODOs:

[WIP] Misc cleanups

---

proxy/src/main/java/com/velocitypowered/proxy/command/ShutdownCommand.java

In "hasPermission" is the removed check already included

Removed a unnecessary check

---

proxy/build.gradle
proxy/src/main/java/com/velocitypowered/proxy/ProxyOptions.java
proxy/src/main/java/com/velocitypowered/proxy/Velocity.java
proxy/src/main/java/com/velocitypowered/proxy/VelocityServer.java

Allow specifying bind port via command line

---

proxy/src/main/java/com/velocitypowered/proxy/protocol/netty/GS4QueryHandler.java

Add "plugins" key before plugins list

Fix GS4 k, v section

---

api/src/main/java/com/velocitypowered/api/event/proxy/ProxyReloadEvent.java
build.gradle
proxy/src/main/java/com/velocitypowered/proxy/VelocityServer.java
proxy/src/main/java/com/velocitypowered/proxy/command/VelocityCommand.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
proxy/src/main/java/com/velocitypowered/proxy/network/ConnectionManager.java

I'm picking up where #120 leaves off. I would like to thank @mikroskeem for his initial work.
Features:

Reload command

---

proxy/src/main/java/com/velocitypowered/proxy/plugin/VelocityEventManager.java

* The first commit addresses a small bug I came across
* The other commits make some small optimisations to the usage of SimpleEventBus
The commit messages should be fairly self explanatory.

Some event bus related fixes

---

api/src/main/java/com/velocitypowered/api/network/ProtocolVersion.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/StateRegistry.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/JoinGame.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/Respawn.java

Support for 1.14 protocol

---

proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/brigadier/ArgumentPropertyRegistry.java

should fix https://pastebin.com/trPsEydb

fix brigadier on 1.14

---

proxy/src/main/java/com/velocitypowered/proxy/VelocityServer.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java

Fixes https://github.com/VelocityPowered/Velocity/issues/178

Wait for player disconnect events on shutdown.

---

proxy/build.gradle
proxy/src/main/resources/log4j2.component.properties

Update to the proper release. Seems like you have already switched to Jansi :)

Update TerminalConsoleAppender to 1.2.0

---

api/src/main/java/com/velocitypowered/api/proxy/server/ServerPing.java
proxy/build.gradle
proxy/src/main/java/com/velocitypowered/proxy/VelocityServer.java
proxy/src/main/java/com/velocitypowered/proxy/config/PingPassthroughMode.java
proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/StatusSessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/network/ConnectionManager.java
proxy/src/main/java/com/velocitypowered/proxy/server/PingSessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/server/VelocityRegisteredServer.java

A more general (and flexible) version of #239.

Ping passthrough

---

api/src/main/java/com/velocitypowered/api/event/player/KickedFromServerEvent.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java

Make plugin can custom redirect message

Allow set redirect message

---

proxy/src/main/java/com/velocitypowered/proxy/connection/backend/BackendPlaySessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/backend/BungeeCordMessageResponder.java
proxy/src/main/java/com/velocitypowered/proxy/connection/backend/VelocityServerConnection.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/util/ByteBufDataInput.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/util/ByteBufDataOutput.java
proxy/src/main/java/com/velocitypowered/proxy/server/VelocityRegisteredServer.java

Fixes #247.
This code needs to be cleaned up, so I'm not merging it right away.

Integrate BungeeQuack functionality into Velocity

---

proxy/src/main/java/com/velocitypowered/proxy/plugin/VelocityPluginManager.java
proxy/src/main/java/com/velocitypowered/proxy/plugin/loader/PluginLoader.java
proxy/src/main/java/com/velocitypowered/proxy/plugin/loader/VelocityPluginContainer.java
proxy/src/main/java/com/velocitypowered/proxy/plugin/loader/java/JavaPluginLoader.java
proxy/src/main/java/com/velocitypowered/proxy/plugin/loader/java/VelocityPluginModule.java

This PR makes `PluginContainer` injectable in a plugin.

Make PluginContainer injectable

---

proxy/src/main/java/com/velocitypowered/proxy/tablist/VelocityTabListLegacy.java

Fixes a small bug where the ping update was sent twice.

Don't send ping update twice (1.7)

---

proxy/src/main/java/com/velocitypowered/proxy/VelocityServer.java
proxy/src/main/java/com/velocitypowered/proxy/connection/backend/VelocityServerConnection.java
proxy/src/main/java/com/velocitypowered/proxy/network/BackendChannelInitializer.java
proxy/src/main/java/com/velocitypowered/proxy/network/BackendChannelInitializerHolder.java
proxy/src/main/java/com/velocitypowered/proxy/network/ConnectionManager.java

Related to ViaVersion/ViaVersion#1550

(Implementation) Allow injecting into backend connection

---

api/src/main/java/com/velocitypowered/api/proxy/config/ProxyConfig.java
proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/LoginSessionHandler.java

Addresses #296 
This PR is basically ready, but I couldn't come up with decent description for the option as there isn't *that* much information available for this in my opinion.
Perhaps option name could be different too?

Add prevent-proxy-connections option

---

api/src/main/java/com/velocitypowered/api/network/ProtocolVersion.java
proxy/build.gradle
proxy/src/main/java/com/velocitypowered/proxy/connection/backend/VelocityServerConnection.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/LoginSessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/registry/DimensionData.java
proxy/src/main/java/com/velocitypowered/proxy/connection/registry/DimensionInfo.java
proxy/src/main/java/com/velocitypowered/proxy/connection/registry/DimensionRegistry.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/ProtocolUtils.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/StateRegistry.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/Chat.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/JoinGame.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/Respawn.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/ServerLoginSuccess.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/brigadier/ArgumentPropertyRegistry.java

I hope this can be at least of some use.
Suggestions and changes are welcome.
Since this is the first time I'm contributing to Velocity please point out loose ends I have left, thanks.

[Future] 1.16 Update

---

proxy/src/main/java/com/velocitypowered/proxy/VelocityServer.java

Fire ProxyShutdownEvent before closing the scheduler / event bus

---

api/src/main/java/com/velocitypowered/api/event/connection/DisconnectEvent.java
proxy/src/main/java/com/velocitypowered/proxy/connection/MinecraftConnection.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/LoginSessionHandler.java

This is a step towards fixing #289 and removing some less-than-optimal behavior in plugins I maintain internally.

Make DisconnectEvent more sane

---

proxy/src/main/java/com/velocitypowered/proxy/config/VelocityConfiguration.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java
proxy/src/main/resources/default-velocity.toml

Basically everything it does, it logs every command execution of a player, even if the command wasn't registered in velocity.
Not sure about the logging format tho. Don't know if @astei is okay with that.

Add logging to command executions by players

---

proxy/src/main/java/com/velocitypowered/proxy/connection/backend/BackendPlaySessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/AvailableCommands.java

Only send the nodes to the player for which he meets the requirement.

Respect nodes' requirements

---

api/src/main/java/com/velocitypowered/api/network/ProtocolVersion.java
proxy/build.gradle
proxy/src/main/java/com/velocitypowered/proxy/VelocityServer.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/registry/DimensionData.java
proxy/src/main/java/com/velocitypowered/proxy/connection/registry/DimensionInfo.java
proxy/src/main/java/com/velocitypowered/proxy/connection/registry/DimensionRegistry.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/ProtocolUtils.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/StateRegistry.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/JoinGame.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/Respawn.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/brigadier/ArgumentPropertyRegistry.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/util/VelocityLegacyHoverEventSerializer.java

This is being prepared so Velocity 1.1.0 has 1.16.2 support ASAP. This is mostly a manual merge of code in #325.

[Future] 1.16.2 for Velocity 1.1.0

---

api/build.gradle
api/src/main/java/com/velocitypowered/api/network/ProtocolVersion.java
proxy/build.gradle
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/registry/DimensionData.java
proxy/src/main/java/com/velocitypowered/proxy/connection/registry/DimensionInfo.java
proxy/src/main/java/com/velocitypowered/proxy/connection/registry/DimensionRegistry.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/ProtocolUtils.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/StateRegistry.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/JoinGame.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/Respawn.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/packet/brigadier/ArgumentPropertyRegistry.java

Pull-request to track 1.16.2 changes.

[Future] 1.16.2

---

api/src/main/java/com/velocitypowered/api/network/ProtocolVersion.java

Will be merged in once 1.16.3 is released.

Minecraft 1.16.3 (for Velocity 1.1.0)

---

api/src/ap/java/com/velocitypowered/api/plugin/ap/PluginAnnotationProcessor.java

added "be lowercase" to the invalid plugin id message

Added lowercase to invalid plugin id message

---

proxy/src/main/java/com/velocitypowered/proxy/VelocityServer.java
proxy/src/main/java/com/velocitypowered/proxy/command/VelocityCommandManager.java
proxy/src/main/java/com/velocitypowered/proxy/command/builtin/GlistCommand.java
proxy/src/main/java/com/velocitypowered/proxy/command/builtin/ServerCommand.java
proxy/src/main/java/com/velocitypowered/proxy/command/builtin/VelocityCommand.java
proxy/src/main/java/com/velocitypowered/proxy/connection/backend/LoginSessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java
proxy/src/main/java/com/velocitypowered/proxy/connection/client/HandshakeSessionHandler.java
proxy/src/main/java/com/velocitypowered/proxy/connection/util/ConnectionMessages.java
proxy/src/main/java/com/velocitypowered/proxy/protocol/util/VelocityLegacyHoverEventSerializer.java

Update for Adventure changes
